var rscK = {
	"l_001_l" : "Annotation-mode button",
	"l_002_l" : "Be first to suggest a feature here!",
	"l_003_l" : "Propose a Feature",
	"l_004_l" : "Features",
	"l_005_l" : "Proposed",
	"l_006_l" : "Public",
	"l_007_l" : "Status unknown",
	"l_008_l" : "view",
	"l_009_l" : "Oops! This functionality has yet to be created. We'll let you know when it is ready!",
	"l_010_l" : "Propose a feature",
	"l_012_l" : "Feature Detail",
	"l_013_l" : "Name",
	"l_014_l" : "Description",
	"l_015_l" : "Status",
	"l_016_l" : "Comments",
	"l_017_l" : "Type your suggestion here",
	"l_018_l" : "Proposed by",
	"l_019_l" : "Submit",
	"l_020_l" : "Add a comment",
	"l_021_l" : "+1",
	"l_022_l" : "Discuss",
	"l_023_l" : "Team Up"
}